In [7]:
import os

print("Current folder:")
print(os.getcwd())

Current folder:
C:\Users\rezau\Saved Games

In [10]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'DATA_CLEANING.ipynb', 'desktop.ini']

In [12]:
import os

print(os.listdir(r"C:\Users\rezau\OneDrive\Desktop\data analysis projects\New folder"))

['.ipynb_checkpoints', 'DATA_CLEANING.ipynb', 'sales_raw_500.xlsx']

In [14]:
import os
print(os.getcwd())

C:\Users\rezau\Saved Games

In [15]:
import os

os.chdir(r"C:\Users\rezau\OneDrive\Desktop\data analysis projects\New folder")

print(os.getcwd())

C:\Users\rezau\OneDrive\Desktop\data analysis projects\New folder

In [19]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
import pandas as pd

df = pd.read_excel("sales_raw_500.xlsx")
df.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001 2023-01-13    Rohit  South   Mobile  23289  19118
1      1002 2023-10-07     Aman   West   Laptop   8905   5593
2      1003 2023-11-05    Rahul  South  Monitor  59987  39959
3      1004 2024-02-19    Rahul  South  Printer  49597  33892
4      1005 2024-01-26   Anjali  North   Laptop  54797  34468

In [21]:
#duplicate removes
df = df.drop_duplicates()

In [22]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [37]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [38]:
df = df.dropna(subset=['Order_Date'])

In [39]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost Order_Data
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118 2023-01-13
1        1002 2023-10-07     Aman   West   Laptop   8905   5593 2023-10-07
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959 2023-11-05
3        1004 2024-02-19    Rahul  South  Printer  49597  33892 2024-02-19
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468 2024-01-26
..        ...        ...      ...    ...      ...    ...    ...        ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931 2023-10-18
495      1496 2023-04-24    Kiran  North  Printer  23434  16388 2023-04-24
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970 2023-06-27
497      1498 2023-05-08     Aman   East   Tablet  19160  15636 2023-05-08
499      1500 2023-10-07    Vikas  North  Printer  34567  22426 2023-10-07

[482 rows x 8 columns]

In [40]:
df.drop(columns=['Order_Data'], inplace=True)

In [41]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [42]:
df['Profit'] = df['Sales'] - df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

In [43]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [44]:
df.to_csv('sales_cleaned.csv',index = False)

In [45]:
import  pandas as pd
from sqlalchemy import create_engine #connection between sql python

In [46]:
df = pd.read_csv('sales_cleaned.csv')

In [47]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
480,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
481,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [48]:
%pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in C:\Users\rezau\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [57]:
engine = create_engine(
    "postgresql+psycopg2://postgres:PostgreRima@localhost:5432/salesdb"
)

In [56]:
import psycopg2

try:
    conn = psycopg2.connect(
        host="localhost",
        port="5432",
        database="salesdb",
        user="postgres",
        password="Postgrerima"   # your password
    )
    print("Connected!")
    conn.close()

except Exception as e:
    print(e)

connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

In [59]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    port="5432",
    database="salesdb",
    user="postgres",
    password="Postgrerima"
)

print("Connected!")
conn.close()

Connected!

In [60]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Postgrerima@localhost:5432/salesdb"
)

In [61]:
df.to_sql('sales_data', engine, if_exists='replace', index=False)

482